apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-cloudflare.yaml
  - helm-external-dns.yaml
  - helm-ingress-nginx.yaml
  - helm-metrics-server.yaml
namespace: flux-system
patches:
  - target:
      kind: HelmRepository
    patch: |-
      - op: replace
        path: /spec/interval
        value: 30m