apiVersion: v1
data:
  cloudflare_credentials.json: ENC[AES256_GCM,data:mUC7LwR2n34zEq56/AwLyufl6v5+DKQlpNGQoivLBFbgc2fPDDYZmlCEn3T5jWl40SqK71g69L2MzkxnV8Wsmcaom1CvNhfvnJQpRYC8vooWyigNsPzeOtk4glE29pCk4MojYv6AUYOquEeTGWXSJDxm9Nb6UQ+zuNsHkfw5KFUh9ehDUyNgXCkSjBiCmAIXb9n9tdRhzkZgI7lV/uhD2itEsnj4B+ZMUrRb2/Fa/4PcVvU95Haj9cJ+DH4XsnZlf5SrgvVr7FaiNiGk1fco5V1EwSQxRgqc,iv:lwto+Ta1VAADwIPtoFr+JyS4oRoEkdoZY0LHs/OaYpM=,tag:ux1ySGHZh4fkYqV+HhSClQ==,type:str]
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qw932v4nt3muyy7lf6f2k68627huql68duzqvq7qq0tljr37cp6sjq07f9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdnVISkVSWTF3ZmY4SzU5
        OFZvbEpzVFN2bmJQVytpSUFWZnJvRkcwZ25rCjlTSVRNYjhmY2VreXVFWXJwUitz
        RmpLVnRyYVp2aFFHQkpUZlhrSEE1SUkKLS0tIGovRHRVeExySmxISmNGOGVaeWRI
        Zyt4Rm92VXN5amM4ZTNoWnEvNVRjUTAK2/+gZo1OYwZ2EXZWzvEPQqwf7w0xO+N5
        W+0ECeNCLxzC1uqzSQFQBIpLYT7hbX/pawTd+pwKNaQA77L2A+5pVw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1rjtye6ftdnlhakmwaly8twan58dcw64mmenm9ap2lteyhux3692su66802
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTjFlSnBNYVVadFpUMTlW
        eDdvbkZZNm1ldVRwS1F4SWx6VWlLQ2pZNmpFCjYvUmsya3dKZys0SjRJczJCcmYx
        MEFNVEhITFNVd3ZxckxZZXU1dFdlN3cKLS0tIE4xS1Z5Z1lHeklsN3BaUFVIMlIz
        TEVhK2RxQ0hWTEcvN21oK0NJTnVJNkkKuPBklpxvtyBoUfJOeCPZhtlYRvYf9CGO
        DfnG8SHrfxAEsNt092pwpk+QpS5QVCvmVvyLkPGmQT8OPY61t0HrtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-14T18:20:00Z"
  mac: ENC[AES256_GCM,data:rmqXtMWj5FiCcKIsjV5j1oFME07WFBO0bqGBdwNY4ZKU9TqNGQDCVft2hItzIE8gzPN7lHmXXOh3js9e5hBDYSQu+z832DuK8aDy74dmNeuRk87MK/uijvwb1U7H+95o/fqmsWKNaRPgQdiu7R664CCmMCynKVoFdTNsYayyWOY=,iv:pDWpke8JOsuu/cxLOPVVnhq+898pUW+ehM4pE7RTRHg=,tag:QYhpSkw2GAKLh9cdLHBOoQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData|key|token|secretboxEncryptionSecret|secret)$
  version: 3.9.4
