apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: "3.10.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  values:
    args:
      - --kubelet-insecure-tls