apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-core
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
    - name: infrastructure-repo
  path: ./infrastructure/app
  patches:
    - target:
        kind: HelmRelease
      patch: |-
        - op: replace
          path: /spec/interval
          value: 30m
        - op: add
          path: /spec/install
          value:
            crds: CreateReplace
            remediation:
              retries: 3
        - op: add
          path: /spec/driftDetection
          value:
            mode: enabled
        - op: add
          path: /spec/upgrade
          value:
            cleanupOnFail: true
            crds: CreateReplace
            remediation:
              strategy: rollback
              retries: 3
        - op: add
          path: /spec/chart/spec/sourceRef/namespace
          value: flux-system
  prune: true
  timeout: 5m
  wait: true

