apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure-repo.yaml
  - infrastructure-core.yaml
  - infrastructure-config.yaml
patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |-
      - op: add
        path: /spec/retryInterval
        value: 5s
      - op: add
        path: /spec/postBuild
        value:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-config
              optional: false
            - kind: Secret
              name: cluster-secrets
              optional: false