apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - applications.yaml
patches:
  - target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
    patch: |-
      - op: add
        path: /spec/retryInterval
        value: 5s
      - op: add
        path: /spec/postBuild
        value:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-config
              optional: false