apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  path: ./infrastructure
  prune: true
  timeout: 5m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false


