apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-repo
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
  path: ./infrastructure/repo
  targetNamespace: flux-system
  patches:
    - target:
        kind: HelmRepository
      patch: |-
        - op: replace
          path: /spec/interval
          value: 30m
  prune: true
  timeout: 5m
  wait: true

