apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure.yaml
patches:
  - target:
      kind: Kustomization
    patch: |-
      - op: add
        path: /spec/postbuild
        value:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-config
              optional: false
            - kind: Secret
              name: cluster-secrets
              optional: false