apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbao
spec:
  releaseName: openbao
  chart:
    spec:
      chart: openbao
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: openbao
  interval: 1h
  values:
      server:
        ingress:
          enabled: true
          hosts:
            - host: "openbao.${DOMAIN}"
      ui:
        enabled: true