apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openbao
spec:
  releaseName: openbao
  chart:
    spec:
      chart: openbao
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: openbao
  interval: 1h
  values:
      server:
        ingress:
          enabled: true
          hosts:
            - host: "openbao.${DOMAIN}"
      ui:
        enabled: true
---
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao-autounseal
spec:
  interval: 15m
  chart:
    spec:
      chart: vault-autounseal
      version: 0.5.3
      sourceRef:
        kind: HelmRepository
        name: pytoshka-vault-autounseal
        namespace: flux-charts
      interval: 15m
  values:
    settings:
      vault_url: 'http://openbao.openbao-system.svc.cluster.local:8200'

      # vault unlocking keys settings:
      vault_secret_shares: 3
      vault_secret_threshold: 2

      # secret for storing vault root token
      vault_root_token_secret: openbao-root-token
      # secret for storing vault unlock keys
      vault_keys_secret: openbao-keys