apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- release.yaml
- repository.yaml
namespace: cloudflare
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: tunnel-credentials
    literals:
      - credentials.json=${cloudflare_credentials_json}