apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: secrets
  path: ./infrastructure
  prune: true
  timeout: 5m
  wait: true
  postBuild:
    substitute:
      CLOUDFLARE_TUNNEL_NAME: "demo-lab"
      CLOUDFLARE_TUNNEL_ID: "tunnel-id"