apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  resources:
    - secrets/cloudflare-secrets.yaml
  prune: true
  timeout: 5m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey
  postBuild:
    substitute:
      CLOUDFLARE_TUNNEL_NAME: "demo-lab"
      CLOUDFLARE_TUNNEL_ID: "tunnel-id"