apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - flux-system
  - ../base

patches:
  - target:
      kind: Kustomization
      name: cluster-secrets
    patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: cluster-secrets
        namespace: flux-system
      spec:
        path: clusters/demo-lab/secrets