apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../base
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: cluster-config
    namespace: flux-system
    envs:
      - configs/cluster-config.env
secretGenerator:
  - name: cluster-secrets
    namespace: flux-system
    envs:
      - secrets/cloudflare.env