apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/demo-lab/secrets
  prune: true
  timeout: 5m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: flux-sops-agekey