apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-system
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: 3
  values:
    controller:
      service:
        type: ClusterIP
      ingressClassResource:
        default: true