apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: kyverno
  interval: 1h
