apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nginx-tunnel-endpoint
spec:
  endpoints:
    - dnsName: \*.${DOMAIN}
      recordType: CNAME
      targets: ["${CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"]
