apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- repo.yaml
- namespace.yaml
- tunnel-secret.yaml
- release.yaml
namespace: cloudflare
generatorOptions:
  disableNameSuffixHash: true