apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare
spec:
  releaseName: cloudflare
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
  interval: 1h

  values:
    cloudflare:
      tunnelName: ${CLOUDFLARE_TUNNEL_NAME}
      tunnelId: ${CLOUDFLARE_TUNNEL_ID}
      secretName: "tunnel-credentials"
      ingress:
        - hostname: "*.${DOMAIN}"
          service: "http://ingress-nginx-controller.ingress-system.svc.cluster.local:80"
#          originRequest:
#            noTLSVerify: true