apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.5.1"  # Specify a version
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
      interval: 1m
  valuesFrom: # Use valuesFrom to load values from a file
    - kind: ConfigMap # Changed to load values from a ConfigMap
      name: cloudflare-values