cloudflare:
  tunnelName: ${CLOUDFLARE_TUNNEL_NAME}
  tunnelId: ${CLOUDFLARE_TUNNEL_ID}
  secretName: "tunnel-credentials"
ingress:
  - hostname: "*.${DOMAIN}"
    service: "https://ingress-nginx-controller.kube-system.svc.cluster.local:443"
    originRequest:
      noTLSVerify: true
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
replicaCount: 1